run:
	GITHUB_APPLICATION_ID=961030 \
	GITHUB_INSTALLATION_ID=53493164 \
	GITHUB_USERNAME=murasame-image-updater \
	GITHUB_CRT_PATH=./config/image-updater.pem \
	LOG_LEVEL=debug \
	CONFIG_PATH=./config/setting.yaml \
	go run cmd/main.go