apiVersion: v1
data:
  setting.yaml: |
    rgistryConfig:
    - regitryURI: 211125717884.dkr.ecr.ap-northeast-1.amazonaws.com/*/$1/$2/$3
      gitHubRepository: github.com/murasame29/image-registry-push-notify/services/$1/$2/$3/overlays/$env
      allowImageTag: regexp:^[0-9a-f]{7,40}$
      denyImageTag: latest
      env:
        211125717884: dev
kind: ConfigMap
metadata:
  name: image-updater-config
