apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: image-updater
  name: image-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-updater
  template:
    metadata:
      labels:
        app: image-updater
    spec:
      containers:
      - image: murasame29/image-updater:0.0.3
        name: image-updater
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: LOG_LEVEL
          value: debug
        - name: CONFIG_PATH
          value: /etc/config/setting.yaml
        - name: GITHUB_CRT_PATH
          value: /etc/crt/image-updater.pem
        - name: GITHUB_USERNAME
          value: murasame-image-updater
        - name: GITHUB_APPLICATION_ID
          value: "961030"
        - name: GITHUB_INSTALLATION_ID
          value: "53493164"
        volumeMounts:
        - name: github-app-crt
          mountPath: /etc/crt
        - name: config
          mountPath: /etc/config
      volumes:
      - name: github-app-crt
        secret:
          secretName: image-updater-github-app-pem
      - name: config
        configMap:
          name: image-updater-config
