apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-updater
    app.kubernetes.io/instance: image-updater
  name: image-updater
  namespace: image-updater
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: image-updater
  type: NodePort
