apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tester
  name: tester
spec:
  containers:
  - image: 211125717884.dkr.ecr.ap-northeast-1.amazonaws.com/example/sample/sample-app/app:1
    name: tester
    command: ["sleep", "360000"]
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
